.
│   ├── Controller.sol
│   └── DelegatedController.sol
├── eth.config.yml
│   └── EvilGauge.sol
│   └── YRegistry.sol
│   ├── CurveYCRVVoter.sol
│   ├── StrategyCreamYFI.sol
│   ├── StrategyCurve3CrvVoterProxy.sol
│   ├── StrategyCurveBTCVoterProxy.sol
│   ├── StrategyCurveBUSDVoterProxy.sol
│   ├── StrategyCurveYVoterProxy.sol
│   ├── StrategyDAICurve.sol
│   ├── StrategyDForceUSDC.sol
│   ├── StrategyDForceUSDT.sol
│   ├── StrategyMKRVaultDAIDelegate.sol
│   ├── StrategyProxy.sol
│   ├── StrategyTUSDCurve.sol
│   ├── StrategyVaultUSDC.sol
│   └── StrategyYFIGovernance.sol
│   └── Token.sol
│   ├── BTCOSMedianizer.sol
│   └── ETHOSMedianizer.sol
    ├── yDelegatedVault.sol
    ├── yVault.sol
    └── yWETH.sol

7 directories, 25 files
