
# GitHub Nodejs CI
name: nodejs

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['14.x']

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true
      - name: npm install, build, and test
        run: |
          npm install
          cd packages/ && npm install && npm run-script setup
          npx truffle compile
        env:
          CI: true
