# CI Security Pass 1

name: security-pipeline

on: [push]

jobs:
  salus_scan_job:
    runs-on: ubuntu-latest
    name: Salus Security Scan Pattern Search
    steps:
    - uses: actions/checkout@v1
    - name: Salus Scan
      id: salus_scan
      uses: federacy/scan-action@0.1.1
      with:
          active_scanners: "\n  - PatternSearch"
          enforced_scanners: "\n  - PatternSearch"
